# The URL the site will be built for
base_url = "https://blog.akhildevelops.co.in"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Description of the blog
description = "An Awsome blog"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Current Theme
theme="radion"

taxonomies=[
    {name="categories"},
    {name="tags"}
]
author = "John Smith"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
[extra]
# Put all your custom variables here
radion_title="Tech Bytes"
paginate_by = 5
comments = false
radion_menu = [
    { url = "$BASE_URL", name = "Home" },
]
favicon=true