base_url = "https://blog.akhildevelops.co.in"
compile_sass = true
description = "An Awsome blog"
build_search_index = true
theme = "radion"
author = "Akhil Teja"


[[taxonomies]]
name = "categories"


[[taxonomies]]
name = "tags"


[markdown.highlighting]
light_theme="github-light"
dark_theme="github-dark"


[extra]
radion_title = "Tech Bytes"
paginate_by = 5
comments = false
favicon = true
latex = true
theme = "toggle"


[[extra.radion_menu]]
url = "$BASE_URL"
name = "Home"
